services:
  app:
    build: .
    command: ["alembic", "upgrade", "head", "&&", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      - DB_URL=sqlite+aiosqlite:///app/db.sqlite3
      - RESOURCE_URL=https://mmf.bsu.by/ru/raspisanie-zanyatij/
    volumes:
      - .:/app
