services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_URL=sqlite+aiosqlite:///app/db.sqlite3
      - RESOURCE_URL=https://mmf.bsu.by/ru/raspisanie-zanyatij/
    volumes:
      - .:/app
